### ISSUE TITLE
Fail to run compile_longobj.sh

### ISSUE THREAD

**Issue by hanwen-sun** [heheda12345/frontend#45]
Hello, I meet some problems while installing magpy. I use a docker with coda version 11.8 and gcc version 11.4.0, I create a conda env with python=3.9.12 and install magpy in this env. I comments the spack commands in compile_longobj.sh because It will go error "**==> Error: Spec 'gcc@11.3.0/ohhhwxj' matches no installed packages.**". 
 However, I still fail with error: 
![image](https://github.com/user-attachments/assets/ace5cd28-b288-4172-ab11-80c53b80b59d)

I want to know If I must use the gcc with version 11.3.0 and run the spack commands in your script, thank you!

**Comment by hanwen-sun** [comment]
What's more, I'm not familiar with spack and I want to know what's 'ohhhwxj' in gcc@11.3.0 /ohhhwxj.

**Comment by heheda12345** [comment]
You can safely remove all spack commands if you have manually installed the dependencies. GCC/CUDA version can be slightly different from the proposed one, but python/pytorch version must match the one suggested in this repo.

**Comment by hanwen-sun** [comment]
Thank you, I use the python/pytorch version suggested, but still can't get ldlong.v3.9.12.so correctly. The error is same as above. I want to know what's the influence of not disabling Python integer cache, will the refgraph go wrong according to the paper.

**Comment by heheda12345** [comment]
Not disabling python integer cache may make the refgraph wrong. You can try to build Python from source with your environment first. The compile_longobj.sh is a subset of building Python from source.

**Comment by hanwen-sun** [comment]
Thank your, I have successfully run magpy.
