### ISSUE TITLE
How can I get the trace time and backend compile time for magpy?

### ISSUE THREAD

**Issue by hanwen-sun** [heheda12345/frontend#47]
I want to compare magpy with dynamo on some specific models. Is there any benchmark? What's more, I want to know how can I get the exact trace time of magpy(exclude the time of backend compile time) and backend compile time of compiling a model, thank you!

**Comment by heheda12345** [comment]
We have similar experiments in our paper. You can find the scripts in the artifact repo https://github.com/heheda12345/MagPy-AE

**Comment by hanwen-sun** [comment]
thank you!
